language: python
dist: xenial   # required for Python >= 3.7
python:
    - "3.5"
    - "3.6"
    - "3.7"
install:
    - sudo apt-get -y update
    - pip install codecov
    - pip install -r requirements.txt
script:
    - nosetests
after_success:
    - codecov
